### ISSUE TITLE
How to use this with https://github.com/PaperMC/paperweight-test-plugin?

### ISSUE THREAD

**Issue by marlester-dev** [jpenilla/reflection-remapper#6]
How to use this with https://github.com/PaperMC/paperweight-test-plugin?
I don't know how to get the mappings file path, there is no doc on it.

**Comment by jpenilla** [comment]
Paper includes the mappings https://github.com/jpenilla/reflection-remapper/blob/master/test-plugin/src/main/java/xyz/jpenilla/reflectionremapper/testplugin/TestPlugin.java#L81

For spigot/craftbukkit you will need to source the mappings yourself.
